import { CURRENT_PROTOCOL_VERSION } from '@/shared/mcp_protocol';

const MCP_PROTOCOL_VERSION = CURRENT_PROTOCOL_VERSION;
const CONFIG_FILENAME = 'mcp.json';

export { CONFIG_FILENAME, MCP_PROTOCOL_VERSION };
